 
name: CI Pipeline 
# Đây là tên pipeline hiển thị trong tab Actions trên git
on:
  push:
    branches: [ main ]
# on: pipeline sẽ chạy khi có hành động xảy ra.

# push: chạy khi bạn đẩy code (push) lên GitHub.

# branches: [ main ]: chỉ chạy nếu bạn push lên nhánh main.
jobs:
  check-html:
# jobs: là nơi định nghĩa các công việc (jobs) cần thực hiện.

# check-html: tên của job này (tùy đặt).
    runs-on: ubuntu-latest
# Chạy job trên máy ảo Linux (Ubuntu mới nhất).
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
# steps: các bước thực hiện trong job.

# name: Checkout code: tên bước.

# uses: actions/checkout@v2: sử dụng action có sẵn để lấy mã từ GitHub repo về máy ảo.

      - name: Check if index.html exists
        run: test -f index.html
# name: mô tả hành động – kiểm tra xem có file index.html hay không.

# run: test -f index.html: dòng lệnh Linux:

# test -f index.html → kiểm tra xem file index.html có tồn tại không.
